[tool.poetry]
name = "src"
version = "0.0.0"
description = ""
authors = ["Gary Verhaegen <gary.verhaegen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
